# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joanna/Desktop/jobs/OnGoing/snapShoot/viv/order-snapshot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joanna/Desktop/jobs/OnGoing/snapShoot/viv/order-snapshot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joanna/Desktop/jobs/OnGoing/snapShoot/viv/order-snapshot/CMakeFiles /Users/joanna/Desktop/jobs/OnGoing/snapShoot/viv/order-snapshot/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joanna/Desktop/jobs/OnGoing/snapShoot/viv/order-snapshot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named order-snapshot

# Build rule for target.
order-snapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 order-snapshot
.PHONY : order-snapshot

# fast build rule for target.
order-snapshot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/build
.PHONY : order-snapshot/fast

#=============================================================================
# Target rules for targets named UNIT_TEST

# Build rule for target.
UNIT_TEST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UNIT_TEST
.PHONY : UNIT_TEST

# fast build rule for target.
UNIT_TEST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/build
.PHONY : UNIT_TEST/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

BookSystem/src/Message.o: BookSystem/src/Message.cpp.o

.PHONY : BookSystem/src/Message.o

# target to build an object file
BookSystem/src/Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Message.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Message.cpp.o
.PHONY : BookSystem/src/Message.cpp.o

BookSystem/src/Message.i: BookSystem/src/Message.cpp.i

.PHONY : BookSystem/src/Message.i

# target to preprocess a source file
BookSystem/src/Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Message.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Message.cpp.i
.PHONY : BookSystem/src/Message.cpp.i

BookSystem/src/Message.s: BookSystem/src/Message.cpp.s

.PHONY : BookSystem/src/Message.s

# target to generate assembly for a file
BookSystem/src/Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Message.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Message.cpp.s
.PHONY : BookSystem/src/Message.cpp.s

BookSystem/src/Order.o: BookSystem/src/Order.cpp.o

.PHONY : BookSystem/src/Order.o

# target to build an object file
BookSystem/src/Order.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Order.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Order.cpp.o
.PHONY : BookSystem/src/Order.cpp.o

BookSystem/src/Order.i: BookSystem/src/Order.cpp.i

.PHONY : BookSystem/src/Order.i

# target to preprocess a source file
BookSystem/src/Order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Order.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Order.cpp.i
.PHONY : BookSystem/src/Order.cpp.i

BookSystem/src/Order.s: BookSystem/src/Order.cpp.s

.PHONY : BookSystem/src/Order.s

# target to generate assembly for a file
BookSystem/src/Order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Order.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Order.cpp.s
.PHONY : BookSystem/src/Order.cpp.s

BookSystem/src/OrderPool.o: BookSystem/src/OrderPool.cpp.o

.PHONY : BookSystem/src/OrderPool.o

# target to build an object file
BookSystem/src/OrderPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderPool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderPool.cpp.o
.PHONY : BookSystem/src/OrderPool.cpp.o

BookSystem/src/OrderPool.i: BookSystem/src/OrderPool.cpp.i

.PHONY : BookSystem/src/OrderPool.i

# target to preprocess a source file
BookSystem/src/OrderPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderPool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderPool.cpp.i
.PHONY : BookSystem/src/OrderPool.cpp.i

BookSystem/src/OrderPool.s: BookSystem/src/OrderPool.cpp.s

.PHONY : BookSystem/src/OrderPool.s

# target to generate assembly for a file
BookSystem/src/OrderPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderPool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderPool.cpp.s
.PHONY : BookSystem/src/OrderPool.cpp.s

BookSystem/src/OrderWrap.o: BookSystem/src/OrderWrap.cpp.o

.PHONY : BookSystem/src/OrderWrap.o

# target to build an object file
BookSystem/src/OrderWrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderWrap.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderWrap.cpp.o
.PHONY : BookSystem/src/OrderWrap.cpp.o

BookSystem/src/OrderWrap.i: BookSystem/src/OrderWrap.cpp.i

.PHONY : BookSystem/src/OrderWrap.i

# target to preprocess a source file
BookSystem/src/OrderWrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderWrap.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderWrap.cpp.i
.PHONY : BookSystem/src/OrderWrap.cpp.i

BookSystem/src/OrderWrap.s: BookSystem/src/OrderWrap.cpp.s

.PHONY : BookSystem/src/OrderWrap.s

# target to generate assembly for a file
BookSystem/src/OrderWrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/OrderWrap.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/OrderWrap.cpp.s
.PHONY : BookSystem/src/OrderWrap.cpp.s

BookSystem/src/Reader.o: BookSystem/src/Reader.cpp.o

.PHONY : BookSystem/src/Reader.o

# target to build an object file
BookSystem/src/Reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Reader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Reader.cpp.o
.PHONY : BookSystem/src/Reader.cpp.o

BookSystem/src/Reader.i: BookSystem/src/Reader.cpp.i

.PHONY : BookSystem/src/Reader.i

# target to preprocess a source file
BookSystem/src/Reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Reader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Reader.cpp.i
.PHONY : BookSystem/src/Reader.cpp.i

BookSystem/src/Reader.s: BookSystem/src/Reader.cpp.s

.PHONY : BookSystem/src/Reader.s

# target to generate assembly for a file
BookSystem/src/Reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Reader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Reader.cpp.s
.PHONY : BookSystem/src/Reader.cpp.s

BookSystem/src/SymbolPool.o: BookSystem/src/SymbolPool.cpp.o

.PHONY : BookSystem/src/SymbolPool.o

# target to build an object file
BookSystem/src/SymbolPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/SymbolPool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/SymbolPool.cpp.o
.PHONY : BookSystem/src/SymbolPool.cpp.o

BookSystem/src/SymbolPool.i: BookSystem/src/SymbolPool.cpp.i

.PHONY : BookSystem/src/SymbolPool.i

# target to preprocess a source file
BookSystem/src/SymbolPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/SymbolPool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/SymbolPool.cpp.i
.PHONY : BookSystem/src/SymbolPool.cpp.i

BookSystem/src/SymbolPool.s: BookSystem/src/SymbolPool.cpp.s

.PHONY : BookSystem/src/SymbolPool.s

# target to generate assembly for a file
BookSystem/src/SymbolPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/SymbolPool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/SymbolPool.cpp.s
.PHONY : BookSystem/src/SymbolPool.cpp.s

BookSystem/src/Writer.o: BookSystem/src/Writer.cpp.o

.PHONY : BookSystem/src/Writer.o

# target to build an object file
BookSystem/src/Writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Writer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Writer.cpp.o
.PHONY : BookSystem/src/Writer.cpp.o

BookSystem/src/Writer.i: BookSystem/src/Writer.cpp.i

.PHONY : BookSystem/src/Writer.i

# target to preprocess a source file
BookSystem/src/Writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Writer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Writer.cpp.i
.PHONY : BookSystem/src/Writer.cpp.i

BookSystem/src/Writer.s: BookSystem/src/Writer.cpp.s

.PHONY : BookSystem/src/Writer.s

# target to generate assembly for a file
BookSystem/src/Writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/Writer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/Writer.cpp.s
.PHONY : BookSystem/src/Writer.cpp.s

BookSystem/src/main.o: BookSystem/src/main.cpp.o

.PHONY : BookSystem/src/main.o

# target to build an object file
BookSystem/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/main.cpp.o
.PHONY : BookSystem/src/main.cpp.o

BookSystem/src/main.i: BookSystem/src/main.cpp.i

.PHONY : BookSystem/src/main.i

# target to preprocess a source file
BookSystem/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/main.cpp.i
.PHONY : BookSystem/src/main.cpp.i

BookSystem/src/main.s: BookSystem/src/main.cpp.s

.PHONY : BookSystem/src/main.s

# target to generate assembly for a file
BookSystem/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/main.cpp.s
.PHONY : BookSystem/src/main.cpp.s

BookSystem/src/symbol.o: BookSystem/src/symbol.cpp.o

.PHONY : BookSystem/src/symbol.o

# target to build an object file
BookSystem/src/symbol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/symbol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/symbol.cpp.o
.PHONY : BookSystem/src/symbol.cpp.o

BookSystem/src/symbol.i: BookSystem/src/symbol.cpp.i

.PHONY : BookSystem/src/symbol.i

# target to preprocess a source file
BookSystem/src/symbol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/symbol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/symbol.cpp.i
.PHONY : BookSystem/src/symbol.cpp.i

BookSystem/src/symbol.s: BookSystem/src/symbol.cpp.s

.PHONY : BookSystem/src/symbol.s

# target to generate assembly for a file
BookSystem/src/symbol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/order-snapshot.dir/build.make CMakeFiles/order-snapshot.dir/BookSystem/src/symbol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/BookSystem/src/symbol.cpp.s
.PHONY : BookSystem/src/symbol.cpp.s

UnitTest/MessageTest.o: UnitTest/MessageTest.cpp.o

.PHONY : UnitTest/MessageTest.o

# target to build an object file
UnitTest/MessageTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/MessageTest.cpp.o
.PHONY : UnitTest/MessageTest.cpp.o

UnitTest/MessageTest.i: UnitTest/MessageTest.cpp.i

.PHONY : UnitTest/MessageTest.i

# target to preprocess a source file
UnitTest/MessageTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/MessageTest.cpp.i
.PHONY : UnitTest/MessageTest.cpp.i

UnitTest/MessageTest.s: UnitTest/MessageTest.cpp.s

.PHONY : UnitTest/MessageTest.s

# target to generate assembly for a file
UnitTest/MessageTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/MessageTest.cpp.s
.PHONY : UnitTest/MessageTest.cpp.s

UnitTest/OrderPoolTest.o: UnitTest/OrderPoolTest.cpp.o

.PHONY : UnitTest/OrderPoolTest.o

# target to build an object file
UnitTest/OrderPoolTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderPoolTest.cpp.o
.PHONY : UnitTest/OrderPoolTest.cpp.o

UnitTest/OrderPoolTest.i: UnitTest/OrderPoolTest.cpp.i

.PHONY : UnitTest/OrderPoolTest.i

# target to preprocess a source file
UnitTest/OrderPoolTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderPoolTest.cpp.i
.PHONY : UnitTest/OrderPoolTest.cpp.i

UnitTest/OrderPoolTest.s: UnitTest/OrderPoolTest.cpp.s

.PHONY : UnitTest/OrderPoolTest.s

# target to generate assembly for a file
UnitTest/OrderPoolTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderPoolTest.cpp.s
.PHONY : UnitTest/OrderPoolTest.cpp.s

UnitTest/OrderTest.o: UnitTest/OrderTest.cpp.o

.PHONY : UnitTest/OrderTest.o

# target to build an object file
UnitTest/OrderTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderTest.cpp.o
.PHONY : UnitTest/OrderTest.cpp.o

UnitTest/OrderTest.i: UnitTest/OrderTest.cpp.i

.PHONY : UnitTest/OrderTest.i

# target to preprocess a source file
UnitTest/OrderTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderTest.cpp.i
.PHONY : UnitTest/OrderTest.cpp.i

UnitTest/OrderTest.s: UnitTest/OrderTest.cpp.s

.PHONY : UnitTest/OrderTest.s

# target to generate assembly for a file
UnitTest/OrderTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderTest.cpp.s
.PHONY : UnitTest/OrderTest.cpp.s

UnitTest/OrderWrapTest.o: UnitTest/OrderWrapTest.cpp.o

.PHONY : UnitTest/OrderWrapTest.o

# target to build an object file
UnitTest/OrderWrapTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderWrapTest.cpp.o
.PHONY : UnitTest/OrderWrapTest.cpp.o

UnitTest/OrderWrapTest.i: UnitTest/OrderWrapTest.cpp.i

.PHONY : UnitTest/OrderWrapTest.i

# target to preprocess a source file
UnitTest/OrderWrapTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderWrapTest.cpp.i
.PHONY : UnitTest/OrderWrapTest.cpp.i

UnitTest/OrderWrapTest.s: UnitTest/OrderWrapTest.cpp.s

.PHONY : UnitTest/OrderWrapTest.s

# target to generate assembly for a file
UnitTest/OrderWrapTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/OrderWrapTest.cpp.s
.PHONY : UnitTest/OrderWrapTest.cpp.s

UnitTest/SymbolPoolTest.o: UnitTest/SymbolPoolTest.cpp.o

.PHONY : UnitTest/SymbolPoolTest.o

# target to build an object file
UnitTest/SymbolPoolTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolPoolTest.cpp.o
.PHONY : UnitTest/SymbolPoolTest.cpp.o

UnitTest/SymbolPoolTest.i: UnitTest/SymbolPoolTest.cpp.i

.PHONY : UnitTest/SymbolPoolTest.i

# target to preprocess a source file
UnitTest/SymbolPoolTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolPoolTest.cpp.i
.PHONY : UnitTest/SymbolPoolTest.cpp.i

UnitTest/SymbolPoolTest.s: UnitTest/SymbolPoolTest.cpp.s

.PHONY : UnitTest/SymbolPoolTest.s

# target to generate assembly for a file
UnitTest/SymbolPoolTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolPoolTest.cpp.s
.PHONY : UnitTest/SymbolPoolTest.cpp.s

UnitTest/SymbolTest.o: UnitTest/SymbolTest.cpp.o

.PHONY : UnitTest/SymbolTest.o

# target to build an object file
UnitTest/SymbolTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolTest.cpp.o
.PHONY : UnitTest/SymbolTest.cpp.o

UnitTest/SymbolTest.i: UnitTest/SymbolTest.cpp.i

.PHONY : UnitTest/SymbolTest.i

# target to preprocess a source file
UnitTest/SymbolTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolTest.cpp.i
.PHONY : UnitTest/SymbolTest.cpp.i

UnitTest/SymbolTest.s: UnitTest/SymbolTest.cpp.s

.PHONY : UnitTest/SymbolTest.s

# target to generate assembly for a file
UnitTest/SymbolTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/SymbolTest.cpp.s
.PHONY : UnitTest/SymbolTest.cpp.s

UnitTest/gtests.o: UnitTest/gtests.cpp.o

.PHONY : UnitTest/gtests.o

# target to build an object file
UnitTest/gtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/gtests.cpp.o
.PHONY : UnitTest/gtests.cpp.o

UnitTest/gtests.i: UnitTest/gtests.cpp.i

.PHONY : UnitTest/gtests.i

# target to preprocess a source file
UnitTest/gtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/gtests.cpp.i
.PHONY : UnitTest/gtests.cpp.i

UnitTest/gtests.s: UnitTest/gtests.cpp.s

.PHONY : UnitTest/gtests.s

# target to generate assembly for a file
UnitTest/gtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST.dir/build.make CMakeFiles/UNIT_TEST.dir/UnitTest/gtests.cpp.s
.PHONY : UnitTest/gtests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... UNIT_TEST"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... order-snapshot"
	@echo "... BookSystem/src/Message.o"
	@echo "... BookSystem/src/Message.i"
	@echo "... BookSystem/src/Message.s"
	@echo "... BookSystem/src/Order.o"
	@echo "... BookSystem/src/Order.i"
	@echo "... BookSystem/src/Order.s"
	@echo "... BookSystem/src/OrderPool.o"
	@echo "... BookSystem/src/OrderPool.i"
	@echo "... BookSystem/src/OrderPool.s"
	@echo "... BookSystem/src/OrderWrap.o"
	@echo "... BookSystem/src/OrderWrap.i"
	@echo "... BookSystem/src/OrderWrap.s"
	@echo "... BookSystem/src/Reader.o"
	@echo "... BookSystem/src/Reader.i"
	@echo "... BookSystem/src/Reader.s"
	@echo "... BookSystem/src/SymbolPool.o"
	@echo "... BookSystem/src/SymbolPool.i"
	@echo "... BookSystem/src/SymbolPool.s"
	@echo "... BookSystem/src/Writer.o"
	@echo "... BookSystem/src/Writer.i"
	@echo "... BookSystem/src/Writer.s"
	@echo "... BookSystem/src/main.o"
	@echo "... BookSystem/src/main.i"
	@echo "... BookSystem/src/main.s"
	@echo "... BookSystem/src/symbol.o"
	@echo "... BookSystem/src/symbol.i"
	@echo "... BookSystem/src/symbol.s"
	@echo "... UnitTest/MessageTest.o"
	@echo "... UnitTest/MessageTest.i"
	@echo "... UnitTest/MessageTest.s"
	@echo "... UnitTest/OrderPoolTest.o"
	@echo "... UnitTest/OrderPoolTest.i"
	@echo "... UnitTest/OrderPoolTest.s"
	@echo "... UnitTest/OrderTest.o"
	@echo "... UnitTest/OrderTest.i"
	@echo "... UnitTest/OrderTest.s"
	@echo "... UnitTest/OrderWrapTest.o"
	@echo "... UnitTest/OrderWrapTest.i"
	@echo "... UnitTest/OrderWrapTest.s"
	@echo "... UnitTest/SymbolPoolTest.o"
	@echo "... UnitTest/SymbolPoolTest.i"
	@echo "... UnitTest/SymbolPoolTest.s"
	@echo "... UnitTest/SymbolTest.o"
	@echo "... UnitTest/SymbolTest.i"
	@echo "... UnitTest/SymbolTest.s"
	@echo "... UnitTest/gtests.o"
	@echo "... UnitTest/gtests.i"
	@echo "... UnitTest/gtests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

